version: '3'

services:
  web:
    build:
      context: .
    env_file: 
    - .env
    ports:
    - "8000:80"
    volumes:
    - .:/var/www
    depends_on:
    - db

  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=senha123
    - MYSQL_USER=dular
    - MYSQL_PASSWORD=senha123
    - MYSQL_DATABASE=dular
    volumes:
    - "mysql_data:/var/lib/mysql"
    - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: { driver: local }